<#
.SYNOPSIS
  Regenerate the LuaLS API hint files from the sol3 binding sources and verify
  they match the committed files (parity guard for gen_engine_lua_api.bat /
  gen_editor_lua_api.bat).

.DESCRIPTION
  Runs Source/Tools/ApiDocGen/generate_api_docs.py over both binding roots into
  temp files, then diffs them against the committed rbfxProjs/EmptyTest/_apidocs
  outputs (ignoring CRLF/LF differences, which git normalizes anyway). It also
  prints the class/member/global coverage counts so a refactor batch can be
  checked for API-surface regressions against the baseline.

  Exit code 0 = generated content matches committed content; 1 = drift.

.EXAMPLE
  powershell -File Source/Tools/LuaBindingCI/check_api_docs.ps1
#>
[CmdletBinding()]
param(
    [string]$RepoRoot
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not $RepoRoot) {
    # scripts live in <repo>/Source/Tools/LuaBindingCI
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
}

$gen    = Join-Path $RepoRoot 'Source/Tools/ApiDocGen/generate_api_docs.py'
$apidocs = Join-Path $RepoRoot 'rbfxProjs/EmptyTest/_apidocs'
$tmp = Join-Path $env:TEMP ("rbfx_apidocs_" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

$targets = @(
    @{ Name = 'engine'; Src = 'Source/LuaScript';              Out = 'engine.d.lua'; Header = $null },
    @{ Name = 'editor'; Src = 'Source/Editor/EditorLuaScript'; Out = 'editor.d.lua'; Header = 'rbfx editor plugin API (Editor.* / imgui.*). Generated by Source/Tools/ApiDocGen. Do not edit by hand.' }
)

function Get-Normalized($path) {
    if (-not (Test-Path $path)) { return '' }
    ((Get-Content -Raw -LiteralPath $path) -replace "`r`n", "`n")
}

$drift = $false
foreach ($t in $targets) {
    $genPath = Join-Path $tmp $t.Out
    if ($t.Header) {
        & python $gen --src $t.Src --out $genPath --header $t.Header
    } else {
        & python $gen --src $t.Src --out $genPath
    }
    if ($LASTEXITCODE -ne 0) { throw "generate_api_docs.py failed for $($t.Name)" }

    $committed = Join-Path $apidocs $t.Out
    $a = Get-Normalized $genPath
    $b = Get-Normalized $committed
    if ($a -ne $b) {
        Write-Host "[DRIFT] $($t.Out) differs from generated output" -ForegroundColor Red
        $drift = $true
    } else {
        Write-Host "[ OK  ] $($t.Out) matches generated output" -ForegroundColor Green
    }
}

Write-Host ''
Write-Host 'Coverage (from generated engine.d.lua):' -ForegroundColor Cyan
$engineGen = Join-Path $tmp 'engine.d.lua'
$classes  = (Select-String -Path $engineGen -Pattern '^---@class ' -AllMatches).Count
$functions = (Select-String -Path $engineGen -Pattern '^function ' -AllMatches).Count
Write-Host "  classes=$classes  functions=$functions"

Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue

if ($drift) {
    Write-Host "`nRESULT: API doc drift detected." -ForegroundColor Red
    exit 1
}
Write-Host "`nRESULT: API docs in parity." -ForegroundColor Green
exit 0
