---@meta rbfx editor plugin API (Editor.* / imgui.*). Generated by Source/Tools/ApiDocGen. Do not edit by hand.

---@class Editor
---@field project EditorProject
---@field selection EditorSelection
---@field tick EditorTick
---@field ui EditorUi
Editor = {}
---@return boolean
function Editor.addMenuItem(...) end
---@return boolean
function Editor.addTab(...) end
---@return boolean
function Editor.addWindow(...) end
---@return boolean
function Editor.build(...) end
function Editor.buildPlatforms(...) end
function Editor.buildStatus(...) end
function Editor.exec(...) end
function Editor.getActiveNode(...) end
function Editor.getActiveScene(...) end
---@return string
function Editor.getProjectDataPath(...) end
---@return string
function Editor.getProjectPath(...) end
function Editor.getSelection(...) end
function Editor.hasProject(...) end
---@return boolean
function Editor.hideWindow(...) end
function Editor.log(...) end
function Editor.logError(...) end
function Editor.logWarning(...) end
function Editor.reloadPlugins(...) end
---@return boolean
function Editor.showWindow(...) end
function Editor.subscribe(...) end
function Editor.unsubscribe(...) end

---@class imgui
imgui = {}
function imgui.ArrowButton(...) end
function imgui.Begin(...) end
function imgui.BeginChild(...) end
function imgui.BeginDragDropSource(...) end
function imgui.BeginDragDropTarget(...) end
function imgui.BeginGroup(...) end
function imgui.BeginListBox(...) end
function imgui.BeginMainMenuBar(...) end
function imgui.BeginMenu(...) end
function imgui.BeginMenuBar(...) end
function imgui.BeginPopup(...) end
function imgui.BeginPopupContextItem(...) end
function imgui.BeginPopupModal(...) end
function imgui.BeginTabBar(...) end
function imgui.BeginTabItem(...) end
function imgui.BeginTooltip(...) end
function imgui.Bullet(...) end
function imgui.BulletText(...) end
function imgui.Button(...) end
function imgui.Checkbox(...) end
function imgui.CloseCurrentPopup(...) end
function imgui.CollapsingHeader(...) end
function imgui.ColorButton(...) end
function imgui.ColorEdit4(...) end
function imgui.Combo(...) end
function imgui.DragFloat(...) end
function imgui.DragInt(...) end
function imgui.Dummy(...) end
function imgui.End(...) end
function imgui.EndChild(...) end
function imgui.EndDragDropSource(...) end
function imgui.EndDragDropTarget(...) end
function imgui.EndGroup(...) end
function imgui.EndListBox(...) end
function imgui.EndMainMenuBar(...) end
function imgui.EndMenu(...) end
function imgui.EndMenuBar(...) end
function imgui.EndPopup(...) end
function imgui.EndTabBar(...) end
function imgui.EndTabItem(...) end
function imgui.EndTooltip(...) end
function imgui.GetContentRegionAvail(...) end
function imgui.GetCursorPos(...) end
function imgui.GetCursorScreenPos(...) end
function imgui.GetFrameCount(...) end
function imgui.GetFrameHeight(...) end
function imgui.GetMousePos(...) end
function imgui.GetTextLineHeight(...) end
function imgui.GetWindowPos(...) end
function imgui.GetWindowSize(...) end
function imgui.Image(...) end
---@return boolean
function imgui.ImageButton(...) end
function imgui.ImageItem(...) end
function imgui.Indent(...) end
function imgui.InputFloat(...) end
function imgui.InputInt(...) end
function imgui.InputPath(...) end
function imgui.InputText(...) end
function imgui.InvisibleButton(...) end
function imgui.IsItemActive(...) end
function imgui.IsItemClicked(...) end
function imgui.IsItemEdited(...) end
function imgui.IsItemFocused(...) end
function imgui.IsItemHovered(...) end
function imgui.IsItemToggledOpen(...) end
function imgui.IsKeyDown(...) end
function imgui.IsKeyPressed(...) end
function imgui.IsMouseClicked(...) end
function imgui.IsMouseDoubleClicked(...) end
function imgui.IsMouseDown(...) end
function imgui.IsPopupOpen(...) end
function imgui.MenuItem(...) end
function imgui.NewLine(...) end
function imgui.OpenPopup(...) end
function imgui.PickPath(...) end
function imgui.PopID(...) end
function imgui.PopItemWidth(...) end
function imgui.PopStyleColor(...) end
function imgui.PopTextWrapPos(...) end
function imgui.ProgressBar(...) end
function imgui.PushID(...) end
function imgui.PushItemWidth(...) end
function imgui.PushStyleColor(...) end
function imgui.PushTextWrapPos(...) end
function imgui.RadioButton(...) end
function imgui.SameLine(...) end
function imgui.Selectable(...) end
function imgui.Separator(...) end
function imgui.SetCursorPos(...) end
function imgui.SetCursorPosX(...) end
function imgui.SetCursorPosY(...) end
function imgui.SetCursorScreenPos(...) end
function imgui.SetDragDropPayload(...) end
function imgui.SetMouseCursor(...) end
function imgui.SetNextItemOpen(...) end
function imgui.SetNextItemWidth(...) end
function imgui.SetNextWindowBgAlpha(...) end
function imgui.SetNextWindowPos(...) end
function imgui.SetNextWindowSize(...) end
function imgui.SetTabItemClosed(...) end
function imgui.SetTooltip(...) end
function imgui.SliderFloat(...) end
function imgui.SliderInt(...) end
function imgui.SmallButton(...) end
function imgui.Spacing(...) end
function imgui.Text(...) end
function imgui.TextColored(...) end
function imgui.TextDisabled(...) end
function imgui.TextWrapped(...) end
function imgui.TreeNode(...) end
function imgui.TreeNodeEx(...) end
function imgui.TreePop(...) end
function imgui.Unindent(...) end
---@return string
function imgui.getVersion(...) end
imgui.Col = 0
imgui.Cond = 0
imgui.Dir = 0
imgui.InputTextFlags = 0
imgui.Key = 0
imgui.MouseButton = 0
imgui.SelectableFlags = 0
imgui.TreeNodeFlags = 0
imgui.WindowFlags = 0

---@class EditorProject
EditorProject = {}
---@return string
function EditorProject.dataPath(...) end
---@return boolean
function EditorProject.hasProject(...) end
---@return boolean
function EditorProject.isDirty(...) end
---@return boolean
function EditorProject.markDirty(...) end
---@return string
function EditorProject.path(...) end
---@return boolean
function EditorProject.save(...) end

---@class EditorSelection
EditorSelection = {}
function EditorSelection.activeNode(...) end
---@return boolean
function EditorSelection.add(...) end
---@return boolean
function EditorSelection.clear(...) end
function EditorSelection.components(...) end
function EditorSelection.nodes(...) end
---@return boolean
function EditorSelection.onChanged(...) end
function EditorSelection.scene(...) end
---@return boolean
function EditorSelection.set(...) end

---@class EditorTick
EditorTick = {}
---@return boolean
function EditorTick.after(...) end
---@return boolean
function EditorTick.cancel(...) end
---@return boolean
function EditorTick.defer(...) end
---@return integer
function EditorTick.every(...) end

---@class EditorUi
EditorUi = {}
---@return boolean
function EditorUi.confirm(...) end
---@return boolean
function EditorUi.input(...) end
---@return boolean
function EditorUi.notify(...) end
