---@meta rbfx API. Generated by Source/Tools/ApiDocGen. Do not edit by hand.

function Abs(...) end
function Clamp(...) end
function Cos(...) end
function CreateScene(...) end
function CreateViewport(...) end
function GetRandomSeed(...) end
---@overload fun(typeName: "Animation", resourceName: string): Animation
---@overload fun(typeName: "AnimationSet2D", resourceName: string): AnimationSet2D
---@overload fun(typeName: "Font", resourceName: string): Font
---@overload fun(typeName: "Image", resourceName: string): Image
---@overload fun(typeName: "InputMap", resourceName: string): InputMap
---@overload fun(typeName: "JSONFile", resourceName: string): JSONFile
---@overload fun(typeName: "Material", resourceName: string): Material
---@overload fun(typeName: "Model", resourceName: string): Model
---@overload fun(typeName: "ParticleEffect", resourceName: string): ParticleEffect
---@overload fun(typeName: "ParticleEffect2D", resourceName: string): ParticleEffect2D
---@overload fun(typeName: "PrefabResource", resourceName: string): PrefabResource
---@overload fun(typeName: "Resource", resourceName: string): Resource
---@overload fun(typeName: "Sound", resourceName: string): Sound
---@overload fun(typeName: "Sprite2D", resourceName: string): Sprite2D
---@overload fun(typeName: "Technique", resourceName: string): Technique
---@overload fun(typeName: "Texture", resourceName: string): Texture
---@overload fun(typeName: "Texture2D", resourceName: string): Texture2D
---@overload fun(typeName: "TmxFile2D", resourceName: string): TmxFile2D
---@overload fun(typeName: "XMLFile", resourceName: string): XMLFile
---@param typeName string
---@param resourceName string
---@return Resource
function GetResource(typeName, resourceName) end
function GetSubsystem(...) end
function GetUIRoot(...) end
function Lerp(...) end
function Max(...) end
function Min(...) end
function Random(...) end
function RandomNormal(...) end
function SetRandomSeed(...) end
function SetViewport(...) end
function Sin(...) end
function SubscribeToEvent(...) end
function UnsubscribeEvent(...) end
function UnsubscribeFromEvent(...) end

---@class AnimatedModel : StaticModel, Drawable, Component, Serializable, Object
AnimatedModel = {}
---@return Skeleton
function AnimatedModel.GetSkeleton(...) end
function AnimatedModel.SetUpdateInvisible(...) end

---@class AnimatedSprite2D : StaticSprite2D, Drawable2D, Drawable, Component, Serializable, Object
AnimatedSprite2D = {}
function AnimatedSprite2D.GetAnimation(...) end
function AnimatedSprite2D.GetAnimationSet(...) end
function AnimatedSprite2D.GetFlipX(...) end
function AnimatedSprite2D.GetFlipY(...) end
function AnimatedSprite2D.SetAnimation(...) end
function AnimatedSprite2D.SetAnimationSet(...) end
function AnimatedSprite2D.SetFlipX(...) end
function AnimatedSprite2D.SetFlipY(...) end
function AnimatedSprite2D.SetSpeed(...) end

---@class Animation : Resource, Object
Animation = {}
function Animation.GetAnimationName(...) end
function Animation.GetLength(...) end

---@class AnimationController : Component, Serializable, Object
AnimationController = {}
function AnimationController.Fade(...) end
---@return number
function AnimationController.GetTime(...) end
function AnimationController.IsPlaying(...) end
function AnimationController.Play(...) end
function AnimationController.PlayExclusive(...) end
function AnimationController.PlayExistingExclusive(...) end
function AnimationController.PlayNew(...) end
function AnimationController.PlayNewExclusive(...) end
function AnimationController.SetSpeed(...) end
function AnimationController.Stop(...) end

---@class AnimationSet2D : Resource, Object
AnimationSet2D = {}
function AnimationSet2D.GetAnimation(...) end
function AnimationSet2D.GetNumAnimations(...) end
function AnimationSet2D.GetSprite(...) end

---@class Audio : Object
Audio = {}
---@return Microphone
function Audio.CreateMicrophone(...) end
function Audio.EnumerateMicrophones(...) end
---@return number
function Audio.GetMasterGain(...) end
function Audio.ResumeAll(...) end
function Audio.SetMasterGain(...) end
function Audio.Stop(...) end

---@class BLEND
BLEND = {}
BLEND.ADD = 0
BLEND.ADDALPHA = 0
BLEND.ALPHA = 0
BLEND.DEFERRED_DECAL = 0
BLEND.INVDESTALPHA = 0
BLEND.MULTIPLY = 0
BLEND.PREMULALPHA = 0
BLEND.REPLACE = 0
BLEND.SUBTRACT = 0
BLEND.SUBTRACTALPHA = 0

---@class BT2D
BT2D = {}
BT2D.DYNAMIC = 0
BT2D.KINEMATIC = 0
BT2D.STATIC = 0

---@class BehaviorNetworkObject : NetworkObject, Component, Serializable, Object
BehaviorNetworkObject = {}
function BehaviorNetworkObject.SetClientPrefab(...) end
function BehaviorNetworkObject.SetOwner(...) end

---@class Billboard
Billboard = {}
Billboard.enabled = nil
Billboard.position = nil
Billboard.rotation = nil
Billboard.size = nil

---@class BillboardSet : Drawable, Component, Serializable, Object
BillboardSet = {}
function BillboardSet.Commit(...) end
function BillboardSet.GetBillboard(...) end
function BillboardSet.GetNumBillboards(...) end
function BillboardSet.SetMaterial(...) end
function BillboardSet.SetNumBillboards(...) end
function BillboardSet.SetSorted(...) end

---@class Bone
Bone = {}
Bone.animated = nil
Bone.name = nil
---@type Node
Bone.node = nil

---@class BorderImage : UIElement, Serializable, Object
BorderImage = {}
function BorderImage.GetTexture(...) end
function BorderImage.SetBlendMode(...) end
function BorderImage.SetFullImageRect(...) end
function BorderImage.SetImageRect(...) end
function BorderImage.SetTexture(...) end

---@class BoundingBox
BoundingBox = {}
function BoundingBox.Center(...) end
function BoundingBox.HalfSize(...) end
function BoundingBox.IsInside(...) end
function BoundingBox.Merged(...) end
function BoundingBox.Size(...) end
BoundingBox.max = nil
BoundingBox.min = nil

---@class BufferedSoundStream : SoundStream
BufferedSoundStream = {}
function BufferedSoundStream.AddData(...) end
function BufferedSoundStream.Clear(...) end
function BufferedSoundStream.GetBufferLength(...) end
function BufferedSoundStream.GetBufferNumBytes(...) end

---@class Button : BorderImage, UIElement, Serializable, Object
Button = {}

---@class CEM
CEM = {}
CEM.ACTIVE = 0
CEM.ALWAYS = 0
CEM.NEVER = 0

---@class CROWD_STATE
CROWD_STATE = {}
CROWD_STATE.INVALID = 0
CROWD_STATE.OFFMESH = 0
CROWD_STATE.WALKING = 0

---@class CT
CT = {}
CT.CONETWIST = 0
CT.HINGE = 0
CT.POINT = 0
CT.SLIDER = 0

---@class Camera : Component, Serializable, Object
Camera = {}
function Camera.GetFarClip(...) end
function Camera.GetFov(...) end
function Camera.GetNearClip(...) end
function Camera.GetScreenRay(...) end
function Camera.GetScreenRayFromMouse(...) end
function Camera.GetZoom(...) end
function Camera.IsOrthographic(...) end
function Camera.ScreenToWorldPoint(...) end
function Camera.SetAspectRatio(...) end
function Camera.SetAutoAspectRatio(...) end
function Camera.SetClipPlane(...) end
function Camera.SetFarClip(...) end
function Camera.SetFillMode(...) end
function Camera.SetFov(...) end
function Camera.SetNearClip(...) end
function Camera.SetOrthoSize(...) end
function Camera.SetOrthographic(...) end
function Camera.SetReflectionPlane(...) end
function Camera.SetUseClipping(...) end
function Camera.SetUseReflection(...) end
function Camera.SetViewMask(...) end
function Camera.SetViewOverrideFlags(...) end
function Camera.SetZoom(...) end
function Camera.WorldToScreenPoint(...) end

---@class CheckBox : BorderImage, UIElement, Serializable, Object
CheckBox = {}
function CheckBox.IsChecked(...) end
function CheckBox.SetChecked(...) end

---@class ClientReplica
ClientReplica = {}
function ClientReplica.GetOwnedNetworkObject(...) end

---@class CollisionBox2D : CollisionShape2D, Component, Serializable, Object
CollisionBox2D = {}
function CollisionBox2D.SetAngle(...) end
function CollisionBox2D.SetCenter(...) end
function CollisionBox2D.SetSize(...) end

---@class CollisionChain2D : CollisionShape2D, Component, Serializable, Object
CollisionChain2D = {}
function CollisionChain2D.SetVertex(...) end
function CollisionChain2D.SetVertexCount(...) end
function CollisionChain2D.SetVertices(...) end

---@class CollisionCircle2D : CollisionShape2D, Component, Serializable, Object
CollisionCircle2D = {}
function CollisionCircle2D.SetCenter(...) end
function CollisionCircle2D.SetRadius(...) end

---@class CollisionEdge2D : CollisionShape2D, Component, Serializable, Object
CollisionEdge2D = {}
function CollisionEdge2D.SetVertices(...) end

---@class CollisionPolygon2D : CollisionShape2D, Component, Serializable, Object
CollisionPolygon2D = {}
function CollisionPolygon2D.SetVertex(...) end
function CollisionPolygon2D.SetVertexCount(...) end
function CollisionPolygon2D.SetVertices(...) end

---@class CollisionShape : Component, Serializable, Object
CollisionShape = {}
function CollisionShape.SetBox(...) end
function CollisionShape.SetCapsule(...) end
function CollisionShape.SetCone(...) end
function CollisionShape.SetConvexHull(...) end
function CollisionShape.SetCylinder(...) end
function CollisionShape.SetSphere(...) end
function CollisionShape.SetTerrain(...) end
function CollisionShape.SetTriangleMesh(...) end

---@class CollisionShape2D : Component, Serializable, Object
CollisionShape2D = {}
function CollisionShape2D.SetCategoryBits(...) end
function CollisionShape2D.SetDensity(...) end
function CollisionShape2D.SetFriction(...) end
function CollisionShape2D.SetGroupIndex(...) end
function CollisionShape2D.SetMaskBits(...) end
function CollisionShape2D.SetRestitution(...) end
function CollisionShape2D.SetTrigger(...) end

---@class Color
Color = {}
function Color.FromHSV(...) end
function Color.Lerp(...) end
function Color.ToHSV(...) end
Color.BLACK = nil
Color.BLUE = nil
Color.CYAN = nil
Color.GRAY = nil
Color.GREEN = nil
Color.MAGENTA = nil
Color.RED = nil
Color.TRANSPARENT = nil
Color.WHITE = nil
Color.YELLOW = nil
Color.a = nil
Color.b = nil
Color.g = nil
Color.r = nil

---@class Component : Serializable, Object
Component = {}
function Component.GetNode(...) end
function Component.IsEnabledEffective(...) end
function Component.Remove(...) end
function Component.SetEnabled(...) end
Component.enabled = nil
Component.id = nil
Component.node = nil
Component.scene = nil

---@class Connection : Object
Connection = {}
function Connection.Disconnect(...) end
function Connection.GetAddress(...) end
function Connection.GetBytesInPerSec(...) end
function Connection.GetBytesOutPerSec(...) end
function Connection.GetPacketsInPerSec(...) end
function Connection.GetPacketsOutPerSec(...) end
function Connection.GetScene(...) end
function Connection.IsConnected(...) end
function Connection.SendMessage(...) end
function Connection.SetScene(...) end
function Connection.ToString(...) end

---@class Console : Object
Console = {}
function Console.IsVisible(...) end
function Console.SetAutoVisibleOnError(...) end
function Console.SetCommandInterpreter(...) end
function Console.SetVisible(...) end
function Console.Toggle(...) end

---@class Constraint : Component, Serializable, Object
Constraint = {}
function Constraint.SetAxis(...) end
function Constraint.SetConstraintType(...) end
function Constraint.SetDisableCollision(...) end
function Constraint.SetHighLimit(...) end
function Constraint.SetLowLimit(...) end
function Constraint.SetOtherAxis(...) end
function Constraint.SetOtherBody(...) end
function Constraint.SetOtherPosition(...) end
function Constraint.SetOtherRotation(...) end
function Constraint.SetPosition(...) end
function Constraint.SetRotation(...) end
function Constraint.SetWorldPosition(...) end

---@class Constraint2D : Component, Serializable, Object
Constraint2D = {}
function Constraint2D.GetOtherBody(...) end
function Constraint2D.GetOwnerBody(...) end
function Constraint2D.SetCollideConnected(...) end
function Constraint2D.SetOtherBody(...) end

---@class ConstraintDistance2D : Constraint2D, Component, Serializable, Object
ConstraintDistance2D = {}
function ConstraintDistance2D.SetDampingRatio(...) end
function ConstraintDistance2D.SetFrequencyHz(...) end
function ConstraintDistance2D.SetLength(...) end
function ConstraintDistance2D.SetOtherBodyAnchor(...) end
function ConstraintDistance2D.SetOwnerBodyAnchor(...) end

---@class ConstraintFriction2D : Constraint2D, Component, Serializable, Object
ConstraintFriction2D = {}
function ConstraintFriction2D.SetAnchor(...) end
function ConstraintFriction2D.SetMaxForce(...) end
function ConstraintFriction2D.SetMaxTorque(...) end

---@class ConstraintGear2D : Constraint2D, Component, Serializable, Object
ConstraintGear2D = {}
function ConstraintGear2D.SetOtherConstraint(...) end
function ConstraintGear2D.SetOwnerConstraint(...) end
function ConstraintGear2D.SetRatio(...) end

---@class ConstraintMotor2D : Constraint2D, Component, Serializable, Object
ConstraintMotor2D = {}
function ConstraintMotor2D.SetAngularOffset(...) end
function ConstraintMotor2D.SetCorrectionFactor(...) end
function ConstraintMotor2D.SetLinearOffset(...) end
function ConstraintMotor2D.SetMaxForce(...) end
function ConstraintMotor2D.SetMaxTorque(...) end

---@class ConstraintMouse2D : Constraint2D, Component, Serializable, Object
ConstraintMouse2D = {}
function ConstraintMouse2D.SetDampingRatio(...) end
function ConstraintMouse2D.SetFrequencyHz(...) end
function ConstraintMouse2D.SetMaxForce(...) end
function ConstraintMouse2D.SetTarget(...) end

---@class ConstraintPrismatic2D : Constraint2D, Component, Serializable, Object
ConstraintPrismatic2D = {}
function ConstraintPrismatic2D.SetAnchor(...) end
function ConstraintPrismatic2D.SetAxis(...) end
function ConstraintPrismatic2D.SetEnableLimit(...) end
function ConstraintPrismatic2D.SetEnableMotor(...) end
function ConstraintPrismatic2D.SetLowerTranslation(...) end
function ConstraintPrismatic2D.SetMaxMotorForce(...) end
function ConstraintPrismatic2D.SetMotorSpeed(...) end
function ConstraintPrismatic2D.SetUpperTranslation(...) end

---@class ConstraintPulley2D : Constraint2D, Component, Serializable, Object
ConstraintPulley2D = {}
function ConstraintPulley2D.SetOtherBodyAnchor(...) end
function ConstraintPulley2D.SetOtherBodyGroundAnchor(...) end
function ConstraintPulley2D.SetOwnerBodyAnchor(...) end
function ConstraintPulley2D.SetOwnerBodyGroundAnchor(...) end
function ConstraintPulley2D.SetRatio(...) end

---@class ConstraintRevolute2D : Constraint2D, Component, Serializable, Object
ConstraintRevolute2D = {}
function ConstraintRevolute2D.SetAnchor(...) end
function ConstraintRevolute2D.SetEnableLimit(...) end
function ConstraintRevolute2D.SetEnableMotor(...) end
function ConstraintRevolute2D.SetLowerAngle(...) end
function ConstraintRevolute2D.SetMaxMotorTorque(...) end
function ConstraintRevolute2D.SetMotorSpeed(...) end
function ConstraintRevolute2D.SetUpperAngle(...) end

---@class ConstraintRope2D : Constraint2D, Component, Serializable, Object
ConstraintRope2D = {}
function ConstraintRope2D.SetMaxLength(...) end
function ConstraintRope2D.SetOtherBodyAnchor(...) end
function ConstraintRope2D.SetOwnerBodyAnchor(...) end

---@class ConstraintWeld2D : Constraint2D, Component, Serializable, Object
ConstraintWeld2D = {}
function ConstraintWeld2D.SetAnchor(...) end
function ConstraintWeld2D.SetDampingRatio(...) end
function ConstraintWeld2D.SetFrequencyHz(...) end

---@class ConstraintWheel2D : Constraint2D, Component, Serializable, Object
ConstraintWheel2D = {}
function ConstraintWheel2D.SetAnchor(...) end
function ConstraintWheel2D.SetAxis(...) end
function ConstraintWheel2D.SetDampingRatio(...) end
function ConstraintWheel2D.SetEnableMotor(...) end
function ConstraintWheel2D.SetFrequencyHz(...) end
function ConstraintWheel2D.SetMaxMotorTorque(...) end
function ConstraintWheel2D.SetMotorSpeed(...) end

---@class CrowdAgent : Component, Serializable, Object
CrowdAgent = {}
function CrowdAgent.GetActualVelocity(...) end
function CrowdAgent.GetAgentState(...) end
function CrowdAgent.GetDesiredVelocity(...) end
function CrowdAgent.GetMaxAccel(...) end
function CrowdAgent.GetMaxSpeed(...) end
function CrowdAgent.GetNavigationQuality(...) end
function CrowdAgent.GetQueryFilterType(...) end
function CrowdAgent.GetRadius(...) end
function CrowdAgent.GetTargetPosition(...) end
function CrowdAgent.SetHeight(...) end
function CrowdAgent.SetMaxAccel(...) end
function CrowdAgent.SetMaxSpeed(...) end
function CrowdAgent.SetNavigationQuality(...) end
function CrowdAgent.SetObstacleAvoidanceType(...) end
function CrowdAgent.SetQueryFilterType(...) end
function CrowdAgent.SetRadius(...) end
function CrowdAgent.SetTargetPosition(...) end
function CrowdAgent.SetTargetVelocity(...) end

---@class CrowdManager : Component, Serializable, Object
CrowdManager = {}
function CrowdManager.DrawDebugGeometry(...) end
function CrowdManager.GetMaxAgents(...) end
---@return table
function CrowdManager.GetObstacleAvoidanceParams(...) end
---@return Vector3
function CrowdManager.GetRandomPointInCircle(...) end
function CrowdManager.ResetCrowdTarget(...) end
function CrowdManager.SetCrowdTarget(...) end
function CrowdManager.SetCrowdVelocity(...) end
function CrowdManager.SetMaxAgentRadius(...) end
function CrowdManager.SetMaxAgents(...) end
function CrowdManager.SetObstacleAvoidanceParams(...) end

---@class Cursor : UIElement, Serializable, Object
Cursor = {}

---@class DebugRenderer : Component, Serializable, Object
DebugRenderer = {}
function DebugRenderer.AddBoundingBox(...) end
function DebugRenderer.AddLine(...) end
function DebugRenderer.AddNode(...) end
function DebugRenderer.AddSphere(...) end

---@class DecalSet : Drawable, Component, Serializable, Object
DecalSet = {}
function DecalSet.AddDecal(...) end
function DecalSet.RemoveAllDecals(...) end
function DecalSet.RemoveDecals(...) end
function DecalSet.SetMaterial(...) end

---@class Drawable : Component, Serializable, Object
Drawable = {}
function Drawable.GetWorldBoundingBox(...) end
function Drawable.SetCastShadows(...) end
function Drawable.SetDrawDistance(...) end
function Drawable.SetEnabled(...) end
function Drawable.SetOccluder(...) end
function Drawable.SetShadowDistance(...) end
function Drawable.SetViewMask(...) end

---@class Drawable2D : Drawable, Component, Serializable, Object
Drawable2D = {}
function Drawable2D.SetLayer(...) end
function Drawable2D.SetOrderInLayer(...) end

---@class DropDownList : BorderImage, UIElement, Serializable, Object
DropDownList = {}
function DropDownList.AddItem(...) end
function DropDownList.GetItem(...) end
function DropDownList.GetNumItems(...) end
function DropDownList.GetSelectedItem(...) end
function DropDownList.GetSelection(...) end
function DropDownList.RemoveAllItems(...) end
function DropDownList.SetSelection(...) end

---@class DynamicNavigationMesh : NavigationMesh, Component, Serializable, Object
DynamicNavigationMesh = {}
function DynamicNavigationMesh.SetDrawObstacles(...) end

---@class Engine : Object
Engine = {}
function Engine.DumpResources(...) end
function Engine.Exit(...) end
function Engine.IsHeadless(...) end

---@class EventData
EventData = {}
function EventData.Contains(...) end

---@class FHL
FHL = {}
FHL.LIGHT = 0
FHL.NONE = 0
FHL.NORMAL = 0

---@class FILTER
FILTER = {}
FILTER.ANISOTROPIC = 0
FILTER.BILINEAR = 0
FILTER.DEFAULT = 0
FILTER.NEAREST = 0
FILTER.TRILINEAR = 0

---@class FM
FM = {}
FM.FOCUSABLE = 0
FM.FOCUSABLE_DEFOCUSABLE = 0
FM.NOTFOCUSABLE = 0
FM.RESETFOCUS = 0

---@class FileSystem : Object
FileSystem = {}
function FileSystem.DirExists(...) end
function FileSystem.FileExists(...) end
---@return string
function FileSystem.GetProgramDir(...) end
---@return string
function FileSystem.GetUserDocumentsDir(...) end

---@class Font : Resource, Object
Font = {}

---@class Geometry
Geometry = {}
function Geometry.GetVertexBuffer(...) end
function Geometry.SetDrawRange(...) end
function Geometry.SetIndexBuffer(...) end
function Geometry.SetLodDistance(...) end
function Geometry.SetVertexBuffer(...) end

---@class Graphics : Object
Graphics = {}
function Graphics.GetHeight(...) end
function Graphics.GetMonitorCount(...) end
function Graphics.GetWidth(...) end
---@return boolean
function Graphics.SetDefaultWindowModes(...) end
function Graphics.SetWindowTitle(...) end
function Graphics.TakeScreenShot(...) end
function Graphics.ToggleFullscreen(...) end
Graphics.windowTitle = nil

---@class HA
HA = {}
HA.CENTER = 0
HA.LEFT = 0
HA.RIGHT = 0

---@class HM
HM = {}
HM.ALWAYS = 0
HM.FOCUS = 0
HM.NEVER = 0

---@class HTTP
HTTP = {}
HTTP.CLOSED = 0
HTTP.ERROR = 0
HTTP.INITIALIZING = 0
HTTP.OPEN = 0

---@class HttpRequest
HttpRequest = {}
function HttpRequest.GetError(...) end
function HttpRequest.GetState(...) end
function HttpRequest.GetStatusCode(...) end
function HttpRequest.IsEof(...) end
function HttpRequest.ReadString(...) end

---@class Image : Resource, Object
Image = {}
function Image.GetComponents(...) end
function Image.GetHeight(...) end
function Image.GetWidth(...) end
function Image.SaveJPG(...) end
function Image.SavePNG(...) end
function Image.SetSize(...) end

---@class IndexBuffer
IndexBuffer = {}
function IndexBuffer.GetIndexCount(...) end
function IndexBuffer.GetIndexSize(...) end
function IndexBuffer.SetDebugName(...) end
function IndexBuffer.SetShadowed(...) end
function IndexBuffer.SetSize(...) end
function IndexBuffer.Update(...) end

---@class Input : Object
Input = {}
function Input.CenterMousePosition(...) end
function Input.GetKeyDown(...) end
function Input.GetKeyFromName(...) end
function Input.GetKeyPress(...) end
function Input.GetMouseButtonDown(...) end
function Input.GetMouseButtonPress(...) end
function Input.GetMouseMode(...) end
function Input.GetMouseMove(...) end
function Input.GetMouseMoveWheel(...) end
function Input.GetMouseMoveX(...) end
function Input.GetMouseMoveY(...) end
function Input.GetMousePosition(...) end
function Input.GetNumJoysticks(...) end
function Input.GetNumTouches(...) end
function Input.GetQualifierDown(...) end
function Input.GetTouch(...) end
function Input.IsMinimized(...) end
function Input.IsMouseGrabbed(...) end
function Input.IsMouseLocked(...) end
function Input.IsMouseVisible(...) end
function Input.SetMouseGrabbed(...) end
function Input.SetMouseMode(...) end
function Input.SetMouseVisible(...) end
function Input.SetToggleFullscreen(...) end

---@class InputMap : Resource, Object
InputMap = {}
---@return number
function InputMap.Evaluate(...) end

---@class IntRect
IntRect = {}
function IntRect.Height(...) end
function IntRect.IsInside(...) end
function IntRect.Size(...) end
function IntRect.Width(...) end
IntRect.ZERO = nil
IntRect.bottom = nil
IntRect.left = nil
IntRect.right = nil
IntRect.top = nil

---@class IntVector2
IntVector2 = {}
function IntVector2.ToVector2(...) end
IntVector2.ONE = nil
IntVector2.ZERO = nil
IntVector2.x = nil
IntVector2.y = nil

---@class IntVector3
IntVector3 = {}
IntVector3.ONE = nil
IntVector3.ZERO = nil
IntVector3.x = nil
IntVector3.y = nil
IntVector3.z = nil

---@class JSONFile : Resource, Object
JSONFile = {}
function JSONFile.FromString(...) end
---@return JSONValue
function JSONFile.GetRoot(...) end

---@class JSONValue
JSONValue = {}
---@return JSONValue
function JSONValue.Get(...) end
function JSONValue.GetBool(...) end
function JSONValue.GetDouble(...) end
function JSONValue.GetFloat(...) end
function JSONValue.GetInt(...) end
function JSONValue.GetString(...) end
function JSONValue.IsArray(...) end
function JSONValue.IsNull(...) end
function JSONValue.IsObject(...) end
function JSONValue.Size(...) end

---@class KEY
KEY = {}
KEY.ALT = 0
KEY.CTRL = 0
KEY.DELETE = 0
KEY.DOWN = 0
KEY.END = 0
KEY.ESC = 0
KEY.F1 = 0
KEY.F10 = 0
KEY.F11 = 0
KEY.F12 = 0
KEY.F2 = 0
KEY.F3 = 0
KEY.F4 = 0
KEY.F5 = 0
KEY.F6 = 0
KEY.F7 = 0
KEY.F8 = 0
KEY.F9 = 0
KEY.HOME = 0
KEY.INSERT = 0
KEY.LEFT = 0
KEY.PAGEDOWN = 0
KEY.PAGEUP = 0
KEY.RETURN = 0
KEY.RIGHT = 0
KEY.SHIFT = 0
KEY.SPACE = 0
KEY.TAB = 0
KEY.UP = 0

---@class LANDiscoveryManager : Object
LANDiscoveryManager = {}
function LANDiscoveryManager.GetBroadcastTimeMs(...) end
function LANDiscoveryManager.SetBroadcastData(...) end
function LANDiscoveryManager.SetBroadcastTimeMs(...) end
function LANDiscoveryManager.Start(...) end
function LANDiscoveryManager.Stop(...) end

---@class LIGHT
LIGHT = {}
LIGHT.DIRECTIONAL = 0
LIGHT.POINT = 0
LIGHT.SPOT = 0

---@class LM
LM = {}
LM.FREE = 0
LM.HORIZONTAL = 0
LM.VERTICAL = 0

---@class LT2D
LT2D = {}
LT2D.IMAGE_LAYER = 0
LT2D.OBJECT_GROUP = 0
LT2D.TILE_LAYER = 0

---@class Light : Drawable, Component, Serializable, Object
Light = {}
function Light.GetBrightness(...) end
function Light.GetColor(...) end
function Light.GetLightType(...) end
function Light.GetRange(...) end
function Light.SetAspectRatio(...) end
function Light.SetBrightness(...) end
function Light.SetCastShadows(...) end
function Light.SetColor(...) end
function Light.SetFov(...) end
function Light.SetLength(...) end
function Light.SetLightType(...) end
function Light.SetRadius(...) end
function Light.SetRampTexture(...) end
function Light.SetRange(...) end
function Light.SetShadowBias(...) end
function Light.SetShadowCascade(...) end
function Light.SetShadowFadeDistance(...) end
function Light.SetShadowIntensity(...) end
function Light.SetShadowNearFarRatio(...) end
function Light.SetShadowResolution(...) end
function Light.SetSpecularIntensity(...) end

---@class LineEdit : UIElement, Serializable, Object
LineEdit = {}
---@return string
function LineEdit.GetText(...) end
function LineEdit.SetText(...) end

---@class ListView : UIElement, Serializable, Object
ListView = {}
function ListView.AddItem(...) end
function ListView.GetItem(...) end
function ListView.GetNumItems(...) end
function ListView.GetSelection(...) end
function ListView.RemoveAllItems(...) end
function ListView.SetHighlightMode(...) end
function ListView.SetSelectOnClickEnd(...) end
function ListView.SetSelection(...) end

---@class Localization : Object
Localization = {}
---@return string
function Localization.GetLanguage(...) end
---@return integer
function Localization.GetLanguageIndex(...) end
function Localization.GetNumLanguages(...) end
---@return string
function Localization.GetString(...) end
function Localization.LoadJSONFile(...) end
function Localization.Reset(...) end
function Localization.SetLanguage(...) end

---@class MM
MM = {}
MM.ABSOLUTE = 0
MM.FREE = 0
MM.INVALID = 0
MM.RELATIVE = 0
MM.WRAP = 0

---@class MOUSEB
MOUSEB = {}
MOUSEB.LEFT = 0
MOUSEB.MIDDLE = 0
MOUSEB.RIGHT = 0
MOUSEB.X1 = 0
MOUSEB.X2 = 0

---@class MSG
MSG = {}
MSG.USER = 0

---@class Material : Resource, Object
Material = {}
---@return Material
function Material.Clone(...) end
function Material.GetNumTechniques(...) end
---@return string
function Material.GetPixelShaderDefines(...) end
---@return string
function Material.GetVertexShaderDefines(...) end
function Material.SetCullMode(...) end
function Material.SetDepthBias(...) end
function Material.SetPixelShaderDefines(...) end
function Material.SetScene(...) end
function Material.SetShaderParameter(...) end
function Material.SetShaderParameterAnimation(...) end
function Material.SetShaderParameterAnimationSpeed(...) end
function Material.SetShaderParameterAnimationWrapMode(...) end
function Material.SetTechnique(...) end
function Material.SetTexture(...) end
function Material.SetVertexShaderDefines(...) end

---@class MemoryBuffer
MemoryBuffer = {}
function MemoryBuffer.IsEof(...) end
function MemoryBuffer.ReadFloat(...) end
function MemoryBuffer.ReadString(...) end
function MemoryBuffer.ReadVLE(...) end
function MemoryBuffer.ReadVector3(...) end

---@class Microphone : Object
Microphone = {}
function Microphone.GetFrequency(...) end
function Microphone.Link(...) end

---@class Model : Resource, Object
Model = {}
---@return Model
function Model.Clone(...) end
function Model.GetGeometry(...) end
function Model.GetNumGeometries(...) end
function Model.SetBoundingBox(...) end
function Model.SetGeometry(...) end
function Model.SetIndexBuffers(...) end
function Model.SetNumGeometries(...) end
function Model.SetVertexBuffers(...) end

---@class MoveAndOrbitComponent : Component, Serializable, Object
MoveAndOrbitComponent = {}
function MoveAndOrbitComponent.GetPitch(...) end
function MoveAndOrbitComponent.GetVelocity(...) end
function MoveAndOrbitComponent.GetYaw(...) end
function MoveAndOrbitComponent.GetYawPitchRotation(...) end
function MoveAndOrbitComponent.SetPitch(...) end
function MoveAndOrbitComponent.SetVelocity(...) end
function MoveAndOrbitComponent.SetYaw(...) end

---@class MoveAndOrbitController : Component, Serializable, Object
MoveAndOrbitController = {}
function MoveAndOrbitController.GetInputMap(...) end
function MoveAndOrbitController.LoadInputMap(...) end

---@class NAV_QUALITY
NAV_QUALITY = {}
NAV_QUALITY.HIGH = 0
NAV_QUALITY.LOW = 0
NAV_QUALITY.MEDIUM = 0

---@class Navigable : Component, Serializable, Object
Navigable = {}

---@class NavigationMesh : Component, Serializable, Object
NavigationMesh = {}
---@return boolean
function NavigationMesh.AddTile(...) end
---@return boolean
function NavigationMesh.Allocate(...) end
---@return boolean
function NavigationMesh.BuildTilesInRegion(...) end
function NavigationMesh.DrawDebugGeometry(...) end
function NavigationMesh.FindNearestPoint(...) end
---@return table
function NavigationMesh.FindPath(...) end
function NavigationMesh.GetAllTileIndices(...) end
function NavigationMesh.GetTileData(...) end
function NavigationMesh.GetTileIndex(...) end
function NavigationMesh.HasTile(...) end
---@return boolean
function NavigationMesh.Rebuild(...) end
function NavigationMesh.RemoveTile(...) end
function NavigationMesh.SetAgentHeight(...) end
function NavigationMesh.SetAgentMaxClimb(...) end
function NavigationMesh.SetAgentMaxSlope(...) end
function NavigationMesh.SetAgentRadius(...) end
function NavigationMesh.SetCellHeight(...) end
function NavigationMesh.SetCellSize(...) end
function NavigationMesh.SetDrawOffMeshConnections(...) end
function NavigationMesh.SetPadding(...) end
function NavigationMesh.SetTileSize(...) end

---@class Network : Object
Network = {}
function Network.BroadcastMessage(...) end
---@return boolean
function Network.Connect(...) end
function Network.Disconnect(...) end
---@return table
function Network.GetClientConnections(...) end
function Network.GetServerConnection(...) end
function Network.IsServerRunning(...) end
function Network.RegisterRemoteEvent(...) end
function Network.SetUpdateFps(...) end
---@return boolean
function Network.StartServer(...) end
function Network.StopServer(...) end

---@class NetworkObject : Component, Serializable, Object
NetworkObject = {}
function NetworkObject.GetNode(...) end

---@class Node : Serializable, Object
Node = {}
function Node.AddChild(...) end
function Node.AddTag(...) end
---@return Node
function Node.Clone(...) end
---@return Node
function Node.CreateChild(...) end
---@overload fun(self: Node, typeName: "AnimatedModel"): AnimatedModel
---@overload fun(self: Node, typeName: "AnimatedSprite2D"): AnimatedSprite2D
---@overload fun(self: Node, typeName: "AnimationController"): AnimationController
---@overload fun(self: Node, typeName: "BehaviorNetworkObject"): BehaviorNetworkObject
---@overload fun(self: Node, typeName: "BillboardSet"): BillboardSet
---@overload fun(self: Node, typeName: "Camera"): Camera
---@overload fun(self: Node, typeName: "CollisionBox2D"): CollisionBox2D
---@overload fun(self: Node, typeName: "CollisionChain2D"): CollisionChain2D
---@overload fun(self: Node, typeName: "CollisionCircle2D"): CollisionCircle2D
---@overload fun(self: Node, typeName: "CollisionEdge2D"): CollisionEdge2D
---@overload fun(self: Node, typeName: "CollisionPolygon2D"): CollisionPolygon2D
---@overload fun(self: Node, typeName: "CollisionShape"): CollisionShape
---@overload fun(self: Node, typeName: "CollisionShape2D"): CollisionShape2D
---@overload fun(self: Node, typeName: "Component"): Component
---@overload fun(self: Node, typeName: "Constraint"): Constraint
---@overload fun(self: Node, typeName: "Constraint2D"): Constraint2D
---@overload fun(self: Node, typeName: "ConstraintDistance2D"): ConstraintDistance2D
---@overload fun(self: Node, typeName: "ConstraintFriction2D"): ConstraintFriction2D
---@overload fun(self: Node, typeName: "ConstraintGear2D"): ConstraintGear2D
---@overload fun(self: Node, typeName: "ConstraintMotor2D"): ConstraintMotor2D
---@overload fun(self: Node, typeName: "ConstraintMouse2D"): ConstraintMouse2D
---@overload fun(self: Node, typeName: "ConstraintPrismatic2D"): ConstraintPrismatic2D
---@overload fun(self: Node, typeName: "ConstraintPulley2D"): ConstraintPulley2D
---@overload fun(self: Node, typeName: "ConstraintRevolute2D"): ConstraintRevolute2D
---@overload fun(self: Node, typeName: "ConstraintRope2D"): ConstraintRope2D
---@overload fun(self: Node, typeName: "ConstraintWeld2D"): ConstraintWeld2D
---@overload fun(self: Node, typeName: "ConstraintWheel2D"): ConstraintWheel2D
---@overload fun(self: Node, typeName: "CrowdAgent"): CrowdAgent
---@overload fun(self: Node, typeName: "CrowdManager"): CrowdManager
---@overload fun(self: Node, typeName: "DebugRenderer"): DebugRenderer
---@overload fun(self: Node, typeName: "DecalSet"): DecalSet
---@overload fun(self: Node, typeName: "Drawable"): Drawable
---@overload fun(self: Node, typeName: "Drawable2D"): Drawable2D
---@overload fun(self: Node, typeName: "DynamicNavigationMesh"): DynamicNavigationMesh
---@overload fun(self: Node, typeName: "Light"): Light
---@overload fun(self: Node, typeName: "MoveAndOrbitComponent"): MoveAndOrbitComponent
---@overload fun(self: Node, typeName: "MoveAndOrbitController"): MoveAndOrbitController
---@overload fun(self: Node, typeName: "Navigable"): Navigable
---@overload fun(self: Node, typeName: "NavigationMesh"): NavigationMesh
---@overload fun(self: Node, typeName: "NetworkObject"): NetworkObject
---@overload fun(self: Node, typeName: "Obstacle"): Obstacle
---@overload fun(self: Node, typeName: "Octree"): Octree
---@overload fun(self: Node, typeName: "OffMeshConnection"): OffMeshConnection
---@overload fun(self: Node, typeName: "ParticleEmitter"): ParticleEmitter
---@overload fun(self: Node, typeName: "ParticleEmitter2D"): ParticleEmitter2D
---@overload fun(self: Node, typeName: "PhysicsWorld"): PhysicsWorld
---@overload fun(self: Node, typeName: "PhysicsWorld2D"): PhysicsWorld2D
---@overload fun(self: Node, typeName: "PrefabReference"): PrefabReference
---@overload fun(self: Node, typeName: "RaycastVehicle"): RaycastVehicle
---@overload fun(self: Node, typeName: "RaycastVehicleWheel"): RaycastVehicleWheel
---@overload fun(self: Node, typeName: "ReplicationManager"): ReplicationManager
---@overload fun(self: Node, typeName: "RibbonTrail"): RibbonTrail
---@overload fun(self: Node, typeName: "RigidBody"): RigidBody
---@overload fun(self: Node, typeName: "RigidBody2D"): RigidBody2D
---@overload fun(self: Node, typeName: "Skybox"): Skybox
---@overload fun(self: Node, typeName: "SoundListener"): SoundListener
---@overload fun(self: Node, typeName: "SoundSource"): SoundSource
---@overload fun(self: Node, typeName: "SoundSource3D"): SoundSource3D
---@overload fun(self: Node, typeName: "StaticModel"): StaticModel
---@overload fun(self: Node, typeName: "StaticModelGroup"): StaticModelGroup
---@overload fun(self: Node, typeName: "StaticSprite2D"): StaticSprite2D
---@overload fun(self: Node, typeName: "StretchableSprite2D"): StretchableSprite2D
---@overload fun(self: Node, typeName: "Terrain"): Terrain
---@overload fun(self: Node, typeName: "Text3D"): Text3D
---@overload fun(self: Node, typeName: "TileMap2D"): TileMap2D
---@overload fun(self: Node, typeName: "TileMapLayer2D"): TileMapLayer2D
---@overload fun(self: Node, typeName: "UIComponent"): UIComponent
---@overload fun(self: Node, typeName: "Zone"): Zone
---@param typeName string
---@return Component
function Node:CreateComponent(typeName) end
---@return Node
function Node.GetChild(...) end
function Node.GetChildren(...) end
function Node.GetChildrenWithComponent(...) end
---@return table
function Node.GetChildrenWithTag(...) end
---@overload fun(self: Node, typeName: "AnimatedModel"): AnimatedModel
---@overload fun(self: Node, typeName: "AnimatedSprite2D"): AnimatedSprite2D
---@overload fun(self: Node, typeName: "AnimationController"): AnimationController
---@overload fun(self: Node, typeName: "BehaviorNetworkObject"): BehaviorNetworkObject
---@overload fun(self: Node, typeName: "BillboardSet"): BillboardSet
---@overload fun(self: Node, typeName: "Camera"): Camera
---@overload fun(self: Node, typeName: "CollisionBox2D"): CollisionBox2D
---@overload fun(self: Node, typeName: "CollisionChain2D"): CollisionChain2D
---@overload fun(self: Node, typeName: "CollisionCircle2D"): CollisionCircle2D
---@overload fun(self: Node, typeName: "CollisionEdge2D"): CollisionEdge2D
---@overload fun(self: Node, typeName: "CollisionPolygon2D"): CollisionPolygon2D
---@overload fun(self: Node, typeName: "CollisionShape"): CollisionShape
---@overload fun(self: Node, typeName: "CollisionShape2D"): CollisionShape2D
---@overload fun(self: Node, typeName: "Component"): Component
---@overload fun(self: Node, typeName: "Constraint"): Constraint
---@overload fun(self: Node, typeName: "Constraint2D"): Constraint2D
---@overload fun(self: Node, typeName: "ConstraintDistance2D"): ConstraintDistance2D
---@overload fun(self: Node, typeName: "ConstraintFriction2D"): ConstraintFriction2D
---@overload fun(self: Node, typeName: "ConstraintGear2D"): ConstraintGear2D
---@overload fun(self: Node, typeName: "ConstraintMotor2D"): ConstraintMotor2D
---@overload fun(self: Node, typeName: "ConstraintMouse2D"): ConstraintMouse2D
---@overload fun(self: Node, typeName: "ConstraintPrismatic2D"): ConstraintPrismatic2D
---@overload fun(self: Node, typeName: "ConstraintPulley2D"): ConstraintPulley2D
---@overload fun(self: Node, typeName: "ConstraintRevolute2D"): ConstraintRevolute2D
---@overload fun(self: Node, typeName: "ConstraintRope2D"): ConstraintRope2D
---@overload fun(self: Node, typeName: "ConstraintWeld2D"): ConstraintWeld2D
---@overload fun(self: Node, typeName: "ConstraintWheel2D"): ConstraintWheel2D
---@overload fun(self: Node, typeName: "CrowdAgent"): CrowdAgent
---@overload fun(self: Node, typeName: "CrowdManager"): CrowdManager
---@overload fun(self: Node, typeName: "DebugRenderer"): DebugRenderer
---@overload fun(self: Node, typeName: "DecalSet"): DecalSet
---@overload fun(self: Node, typeName: "Drawable"): Drawable
---@overload fun(self: Node, typeName: "Drawable2D"): Drawable2D
---@overload fun(self: Node, typeName: "DynamicNavigationMesh"): DynamicNavigationMesh
---@overload fun(self: Node, typeName: "Light"): Light
---@overload fun(self: Node, typeName: "MoveAndOrbitComponent"): MoveAndOrbitComponent
---@overload fun(self: Node, typeName: "MoveAndOrbitController"): MoveAndOrbitController
---@overload fun(self: Node, typeName: "Navigable"): Navigable
---@overload fun(self: Node, typeName: "NavigationMesh"): NavigationMesh
---@overload fun(self: Node, typeName: "NetworkObject"): NetworkObject
---@overload fun(self: Node, typeName: "Obstacle"): Obstacle
---@overload fun(self: Node, typeName: "Octree"): Octree
---@overload fun(self: Node, typeName: "OffMeshConnection"): OffMeshConnection
---@overload fun(self: Node, typeName: "ParticleEmitter"): ParticleEmitter
---@overload fun(self: Node, typeName: "ParticleEmitter2D"): ParticleEmitter2D
---@overload fun(self: Node, typeName: "PhysicsWorld"): PhysicsWorld
---@overload fun(self: Node, typeName: "PhysicsWorld2D"): PhysicsWorld2D
---@overload fun(self: Node, typeName: "PrefabReference"): PrefabReference
---@overload fun(self: Node, typeName: "RaycastVehicle"): RaycastVehicle
---@overload fun(self: Node, typeName: "RaycastVehicleWheel"): RaycastVehicleWheel
---@overload fun(self: Node, typeName: "ReplicationManager"): ReplicationManager
---@overload fun(self: Node, typeName: "RibbonTrail"): RibbonTrail
---@overload fun(self: Node, typeName: "RigidBody"): RigidBody
---@overload fun(self: Node, typeName: "RigidBody2D"): RigidBody2D
---@overload fun(self: Node, typeName: "Skybox"): Skybox
---@overload fun(self: Node, typeName: "SoundListener"): SoundListener
---@overload fun(self: Node, typeName: "SoundSource"): SoundSource
---@overload fun(self: Node, typeName: "SoundSource3D"): SoundSource3D
---@overload fun(self: Node, typeName: "StaticModel"): StaticModel
---@overload fun(self: Node, typeName: "StaticModelGroup"): StaticModelGroup
---@overload fun(self: Node, typeName: "StaticSprite2D"): StaticSprite2D
---@overload fun(self: Node, typeName: "StretchableSprite2D"): StretchableSprite2D
---@overload fun(self: Node, typeName: "Terrain"): Terrain
---@overload fun(self: Node, typeName: "Text3D"): Text3D
---@overload fun(self: Node, typeName: "TileMap2D"): TileMap2D
---@overload fun(self: Node, typeName: "TileMapLayer2D"): TileMapLayer2D
---@overload fun(self: Node, typeName: "UIComponent"): UIComponent
---@overload fun(self: Node, typeName: "Zone"): Zone
---@param typeName string
---@return Component
function Node:GetComponent(typeName) end
function Node.GetComponents(...) end
---@return string
function Node.GetName(...) end
function Node.GetNumChildren(...) end
---@overload fun(self: Node, typeName: "AnimatedModel"): AnimatedModel
---@overload fun(self: Node, typeName: "AnimatedSprite2D"): AnimatedSprite2D
---@overload fun(self: Node, typeName: "AnimationController"): AnimationController
---@overload fun(self: Node, typeName: "BehaviorNetworkObject"): BehaviorNetworkObject
---@overload fun(self: Node, typeName: "BillboardSet"): BillboardSet
---@overload fun(self: Node, typeName: "Camera"): Camera
---@overload fun(self: Node, typeName: "CollisionBox2D"): CollisionBox2D
---@overload fun(self: Node, typeName: "CollisionChain2D"): CollisionChain2D
---@overload fun(self: Node, typeName: "CollisionCircle2D"): CollisionCircle2D
---@overload fun(self: Node, typeName: "CollisionEdge2D"): CollisionEdge2D
---@overload fun(self: Node, typeName: "CollisionPolygon2D"): CollisionPolygon2D
---@overload fun(self: Node, typeName: "CollisionShape"): CollisionShape
---@overload fun(self: Node, typeName: "CollisionShape2D"): CollisionShape2D
---@overload fun(self: Node, typeName: "Component"): Component
---@overload fun(self: Node, typeName: "Constraint"): Constraint
---@overload fun(self: Node, typeName: "Constraint2D"): Constraint2D
---@overload fun(self: Node, typeName: "ConstraintDistance2D"): ConstraintDistance2D
---@overload fun(self: Node, typeName: "ConstraintFriction2D"): ConstraintFriction2D
---@overload fun(self: Node, typeName: "ConstraintGear2D"): ConstraintGear2D
---@overload fun(self: Node, typeName: "ConstraintMotor2D"): ConstraintMotor2D
---@overload fun(self: Node, typeName: "ConstraintMouse2D"): ConstraintMouse2D
---@overload fun(self: Node, typeName: "ConstraintPrismatic2D"): ConstraintPrismatic2D
---@overload fun(self: Node, typeName: "ConstraintPulley2D"): ConstraintPulley2D
---@overload fun(self: Node, typeName: "ConstraintRevolute2D"): ConstraintRevolute2D
---@overload fun(self: Node, typeName: "ConstraintRope2D"): ConstraintRope2D
---@overload fun(self: Node, typeName: "ConstraintWeld2D"): ConstraintWeld2D
---@overload fun(self: Node, typeName: "ConstraintWheel2D"): ConstraintWheel2D
---@overload fun(self: Node, typeName: "CrowdAgent"): CrowdAgent
---@overload fun(self: Node, typeName: "CrowdManager"): CrowdManager
---@overload fun(self: Node, typeName: "DebugRenderer"): DebugRenderer
---@overload fun(self: Node, typeName: "DecalSet"): DecalSet
---@overload fun(self: Node, typeName: "Drawable"): Drawable
---@overload fun(self: Node, typeName: "Drawable2D"): Drawable2D
---@overload fun(self: Node, typeName: "DynamicNavigationMesh"): DynamicNavigationMesh
---@overload fun(self: Node, typeName: "Light"): Light
---@overload fun(self: Node, typeName: "MoveAndOrbitComponent"): MoveAndOrbitComponent
---@overload fun(self: Node, typeName: "MoveAndOrbitController"): MoveAndOrbitController
---@overload fun(self: Node, typeName: "Navigable"): Navigable
---@overload fun(self: Node, typeName: "NavigationMesh"): NavigationMesh
---@overload fun(self: Node, typeName: "NetworkObject"): NetworkObject
---@overload fun(self: Node, typeName: "Obstacle"): Obstacle
---@overload fun(self: Node, typeName: "Octree"): Octree
---@overload fun(self: Node, typeName: "OffMeshConnection"): OffMeshConnection
---@overload fun(self: Node, typeName: "ParticleEmitter"): ParticleEmitter
---@overload fun(self: Node, typeName: "ParticleEmitter2D"): ParticleEmitter2D
---@overload fun(self: Node, typeName: "PhysicsWorld"): PhysicsWorld
---@overload fun(self: Node, typeName: "PhysicsWorld2D"): PhysicsWorld2D
---@overload fun(self: Node, typeName: "PrefabReference"): PrefabReference
---@overload fun(self: Node, typeName: "RaycastVehicle"): RaycastVehicle
---@overload fun(self: Node, typeName: "RaycastVehicleWheel"): RaycastVehicleWheel
---@overload fun(self: Node, typeName: "ReplicationManager"): ReplicationManager
---@overload fun(self: Node, typeName: "RibbonTrail"): RibbonTrail
---@overload fun(self: Node, typeName: "RigidBody"): RigidBody
---@overload fun(self: Node, typeName: "RigidBody2D"): RigidBody2D
---@overload fun(self: Node, typeName: "Skybox"): Skybox
---@overload fun(self: Node, typeName: "SoundListener"): SoundListener
---@overload fun(self: Node, typeName: "SoundSource"): SoundSource
---@overload fun(self: Node, typeName: "SoundSource3D"): SoundSource3D
---@overload fun(self: Node, typeName: "StaticModel"): StaticModel
---@overload fun(self: Node, typeName: "StaticModelGroup"): StaticModelGroup
---@overload fun(self: Node, typeName: "StaticSprite2D"): StaticSprite2D
---@overload fun(self: Node, typeName: "StretchableSprite2D"): StretchableSprite2D
---@overload fun(self: Node, typeName: "Terrain"): Terrain
---@overload fun(self: Node, typeName: "Text3D"): Text3D
---@overload fun(self: Node, typeName: "TileMap2D"): TileMap2D
---@overload fun(self: Node, typeName: "TileMapLayer2D"): TileMapLayer2D
---@overload fun(self: Node, typeName: "UIComponent"): UIComponent
---@overload fun(self: Node, typeName: "Zone"): Zone
---@param typeName string
---@return Component
function Node:GetOrCreateComponent(typeName) end
---@return Vector3
function Node.GetPosition(...) end
---@return Vector2
function Node.GetPosition2D(...) end
---@return Quaternion
function Node.GetRotation(...) end
---@return Vector3
function Node.GetScale(...) end
function Node.GetVar(...) end
function Node.GetWorldDirection(...) end
function Node.GetWorldPosition(...) end
---@return Vector2
function Node.GetWorldPosition2D(...) end
function Node.GetWorldRight(...) end
function Node.GetWorldRotation(...) end
function Node.GetWorldUp(...) end
---@return boolean
function Node.HasComponent(...) end
function Node.HasTag(...) end
---@return Node
function Node.InstantiatePrefab(...) end
---@return Vector3
function Node.LocalToWorld(...) end
function Node.LookAt(...) end
function Node.Pitch(...) end
function Node.Remove(...) end
function Node.RemoveAllChildren(...) end
function Node.RemoveChild(...) end
function Node.RemoveComponent(...) end
function Node.Roll(...) end
function Node.Rotate(...) end
function Node.RotateAround(...) end
function Node.Scale2D(...) end
function Node.SetDirection(...) end
function Node.SetEnabled(...) end
function Node.SetName(...) end
function Node.SetParent(...) end
function Node.SetPosition(...) end
function Node.SetPosition2D(...) end
function Node.SetRotation(...) end
function Node.SetScale(...) end
function Node.SetScale2D(...) end
function Node.SetTemporary(...) end
function Node.SetTransform(...) end
function Node.SetTransform2D(...) end
function Node.SetVar(...) end
function Node.SetWorldPosition(...) end
function Node.SetWorldRotation(...) end
function Node.Translate(...) end
function Node.Translate2D(...) end
---@return Vector3
function Node.WorldToLocal(...) end
function Node.Yaw(...) end
---@type Vector3
Node.direction = nil
---@type boolean
Node.enabled = nil
---@type integer
Node.id = nil
---@type string
Node.name = nil
---@type integer
Node.numChildren = nil
---@type integer
Node.numComponents = nil
---@type Node
Node.parent = nil
---@type Vector3
Node.position = nil
---@type Quaternion
Node.rotation = nil
---@type number
Node.rotation2D = nil
---@type Vector3
Node.scale = nil
---@type Scene
Node.scene = nil
---@type Vector3
Node.worldDirection = nil
---@type Vector3
Node.worldPosition = nil
---@type Quaternion
Node.worldRotation = nil
---@type Vector3
Node.worldScale = nil

---@class ORIENT2D
ORIENT2D = {}
ORIENT2D.HEXAGONAL = 0
ORIENT2D.ISOMETRIC = 0
ORIENT2D.ORTHOGONAL = 0
ORIENT2D.STAGGERED = 0

---@class OT2D
OT2D = {}
OT2D.ELLIPSE = 0
OT2D.POLYGON = 0
OT2D.POLYLINE = 0
OT2D.RECTANGLE = 0
OT2D.TILE = 0

---@class Object
Object = {}
---@return string
function Object.GetCategory(...) end
function Object.GetContext(...) end
function Object.GetType(...) end
---@return string
function Object.GetTypeName(...) end

---@class ObjectRef
ObjectRef = {}
function ObjectRef.CastTo(...) end
function ObjectRef.Get(...) end
function ObjectRef.GetAttribute(...) end
function ObjectRef.GetAttributes(...) end
---@return string
function ObjectRef.GetTypeName(...) end
function ObjectRef.SetAttribute(...) end

---@class Obstacle : Component, Serializable, Object
Obstacle = {}
function Obstacle.GetHeight(...) end
function Obstacle.GetRadius(...) end
function Obstacle.SetHeight(...) end
function Obstacle.SetRadius(...) end

---@class Octree : Component, Serializable, Object
Octree = {}
function Octree.RaycastSingle(...) end

---@class OffMeshConnection : Component, Serializable, Object
OffMeshConnection = {}
function OffMeshConnection.GetEndPoint(...) end
function OffMeshConnection.SetBidirectional(...) end
function OffMeshConnection.SetEndPoint(...) end
function OffMeshConnection.SetMask(...) end
function OffMeshConnection.SetRadius(...) end

---@class ParticleEffect : Resource, Object
ParticleEffect = {}

---@class ParticleEffect2D : Resource, Object
ParticleEffect2D = {}

---@class ParticleEmitter : BillboardSet, Drawable, Component, Serializable, Object
ParticleEmitter = {}
function ParticleEmitter.IsEmitting(...) end
function ParticleEmitter.SetEffect(...) end
function ParticleEmitter.SetEmitting(...) end

---@class ParticleEmitter2D : Drawable2D, Drawable, Component, Serializable, Object
ParticleEmitter2D = {}
function ParticleEmitter2D.GetEffect(...) end
function ParticleEmitter2D.IsEmitting(...) end
function ParticleEmitter2D.SetEffect(...) end
function ParticleEmitter2D.SetEmitting(...) end
function ParticleEmitter2D.SetSprite(...) end

---@class PhysicsWorld : Component, Serializable, Object
PhysicsWorld = {}
function PhysicsWorld.DrawDebugGeometry(...) end
function PhysicsWorld.GetGravity(...) end
function PhysicsWorld.RaycastSingle(...) end
function PhysicsWorld.SetFps(...) end
function PhysicsWorld.SetGravity(...) end
function PhysicsWorld.SetInternalEdge(...) end
function PhysicsWorld.SetInterpolation(...) end
function PhysicsWorld.SetMaxSubSteps(...) end
function PhysicsWorld.SetNumIterations(...) end
function PhysicsWorld.SetSplitImpulse(...) end

---@class PhysicsWorld2D : Component, Serializable, Object
PhysicsWorld2D = {}
function PhysicsWorld2D.DrawDebugGeometry(...) end
function PhysicsWorld2D.GetGravity(...) end
---@return table
function PhysicsWorld2D.GetRigidBodies(...) end
function PhysicsWorld2D.GetRigidBody(...) end
function PhysicsWorld2D.SetAllowSleeping(...) end
function PhysicsWorld2D.SetAutoClearForces(...) end
function PhysicsWorld2D.SetDrawAabb(...) end
function PhysicsWorld2D.SetDrawCenterOfMass(...) end
function PhysicsWorld2D.SetDrawJoint(...) end
function PhysicsWorld2D.SetDrawPair(...) end
function PhysicsWorld2D.SetDrawShape(...) end
function PhysicsWorld2D.SetGravity(...) end
function PhysicsWorld2D.SetPositionIterations(...) end
function PhysicsWorld2D.SetSubStepping(...) end
function PhysicsWorld2D.SetVelocityIterations(...) end

---@class Plane
Plane = {}
function Plane.Distance(...) end
Plane.d = nil
Plane.normal = nil

---@class PrefabReference : Component, Serializable, Object
PrefabReference = {}
function PrefabReference.InlineAggressive(...) end
function PrefabReference.SetPrefab(...) end

---@class PrefabResource : Resource, Object
PrefabResource = {}

---@class QUAL
QUAL = {}
QUAL.ALT = 0
QUAL.ANY = 0
QUAL.CTRL = 0
QUAL.NONE = 0
QUAL.SHIFT = 0

---@class Quaternion
Quaternion = {}
function Quaternion.Conjugate(...) end
function Quaternion.FromAngleAxis(...) end
function Quaternion.FromAxes(...) end
function Quaternion.FromEulerAngles(...) end
function Quaternion.FromRotationTo(...) end
function Quaternion.Inverse(...) end
function Quaternion.Normalized(...) end
function Quaternion.PitchAngle(...) end
function Quaternion.RollAngle(...) end
function Quaternion.Slerp(...) end
function Quaternion.YawAngle(...) end
Quaternion.IDENTITY = nil
Quaternion.w = nil
Quaternion.x = nil
Quaternion.y = nil
Quaternion.z = nil

---@class REMOVE
REMOVE = {}
REMOVE.COMPONENT = 0
REMOVE.DISABLED = 0
REMOVE.NODE = 0

---@class Ray
Ray = {}
function Ray.ClosestPoint(...) end
function Ray.HitDistance(...) end
Ray.direction = nil
Ray.origin = nil

---@class RaycastVehicle : Component, Serializable, Object
RaycastVehicle = {}
function RaycastVehicle.AddWheel(...) end
function RaycastVehicle.GetBrakingForce(...) end
function RaycastVehicle.GetEngineForce(...) end
function RaycastVehicle.GetMaxSideSlipSpeed(...) end
function RaycastVehicle.GetNumWheels(...) end
function RaycastVehicle.GetWheel(...) end
function RaycastVehicle.Init(...) end
function RaycastVehicle.RemoveWheel(...) end
function RaycastVehicle.ResetSuspension(...) end
function RaycastVehicle.ResetWheels(...) end
function RaycastVehicle.SetBrakingForce(...) end
function RaycastVehicle.SetEngineForce(...) end
function RaycastVehicle.SetInAirRPM(...) end
function RaycastVehicle.SetMaxSideSlipSpeed(...) end
function RaycastVehicle.UpdateInput(...) end

---@class RaycastVehicleWheel : Component, Serializable, Object
RaycastVehicleWheel = {}
function RaycastVehicleWheel.DrawDebugGeometry(...) end
function RaycastVehicleWheel.GetAxle(...) end
function RaycastVehicleWheel.GetBrakeValue(...) end
function RaycastVehicleWheel.GetConnectionPoint(...) end
function RaycastVehicleWheel.GetContactPosition(...) end
function RaycastVehicleWheel.GetDirection(...) end
function RaycastVehicleWheel.GetRadius(...) end
function RaycastVehicleWheel.GetRotation(...) end
function RaycastVehicleWheel.GetSkidInfoCumulative(...) end
function RaycastVehicleWheel.GetSuspensionRestLength(...) end
function RaycastVehicleWheel.IsInContact(...) end
function RaycastVehicleWheel.SetAxle(...) end
function RaycastVehicleWheel.SetBrakeFactor(...) end
function RaycastVehicleWheel.SetBrakeValue(...) end
function RaycastVehicleWheel.SetConnectionPoint(...) end
function RaycastVehicleWheel.SetDampingCompression(...) end
function RaycastVehicleWheel.SetDampingRelaxation(...) end
function RaycastVehicleWheel.SetDirection(...) end
function RaycastVehicleWheel.SetEngineFactor(...) end
function RaycastVehicleWheel.SetEngineForce(...) end
function RaycastVehicleWheel.SetFrictionSlip(...) end
function RaycastVehicleWheel.SetOffset(...) end
function RaycastVehicleWheel.SetRadius(...) end
function RaycastVehicleWheel.SetRollInfluence(...) end
function RaycastVehicleWheel.SetRotation(...) end
function RaycastVehicleWheel.SetSteeringFactor(...) end
function RaycastVehicleWheel.SetSteeringValue(...) end
function RaycastVehicleWheel.SetSuspensionRestLength(...) end
function RaycastVehicleWheel.SetSuspensionStiffness(...) end

---@class Rect
Rect = {}
function Rect.Center(...) end
function Rect.IsInside(...) end
function Rect.Size(...) end
Rect.FULL = nil
Rect.POSITIVE = nil
Rect.ZERO = nil
Rect.max = nil
Rect.min = nil

---@class RenderDevice : Object
RenderDevice = {}
---@return integer
function RenderDevice.GetClosestFullscreenModeIndex(...) end
---@return number
function RenderDevice.GetDpiScale(...) end
---@return table
function RenderDevice.GetFullscreenModes(...) end
---@return IntVector2
function RenderDevice.GetSwapChainSize(...) end
---@return table
function RenderDevice.GetWindowSettings(...) end

---@class RenderSurface
RenderSurface = {}
function RenderSurface.GetViewport(...) end
function RenderSurface.SetViewport(...) end

---@class Renderer : Object
Renderer = {}
function Renderer.DrawDebugGeometry(...) end
function Renderer.GetDefaultZone(...) end
function Renderer.GetNumViewports(...) end
function Renderer.GetViewport(...) end
function Renderer.SetTextureAnisotropy(...) end
function Renderer.SetTextureFilterMode(...) end
function Renderer.SetTextureQuality(...) end
function Renderer.SetViewport(...) end

---@class ReplicationManager : Component, Serializable, Object
ReplicationManager = {}
function ReplicationManager.GetClientReplica(...) end

---@class Resource : Object
Resource = {}
function Resource.GetMemoryUse(...) end
---@return string
function Resource.GetName(...) end
function Resource.SetName(...) end
---@type string
Resource.name = nil

---@class ResourceCache : Object
ResourceCache = {}
function ResourceCache.Exists(...) end
---@overload fun(self: ResourceCache, typeName: "Animation", resourceName: string): Animation
---@overload fun(self: ResourceCache, typeName: "AnimationSet2D", resourceName: string): AnimationSet2D
---@overload fun(self: ResourceCache, typeName: "Font", resourceName: string): Font
---@overload fun(self: ResourceCache, typeName: "Image", resourceName: string): Image
---@overload fun(self: ResourceCache, typeName: "InputMap", resourceName: string): InputMap
---@overload fun(self: ResourceCache, typeName: "JSONFile", resourceName: string): JSONFile
---@overload fun(self: ResourceCache, typeName: "Material", resourceName: string): Material
---@overload fun(self: ResourceCache, typeName: "Model", resourceName: string): Model
---@overload fun(self: ResourceCache, typeName: "ParticleEffect", resourceName: string): ParticleEffect
---@overload fun(self: ResourceCache, typeName: "ParticleEffect2D", resourceName: string): ParticleEffect2D
---@overload fun(self: ResourceCache, typeName: "PrefabResource", resourceName: string): PrefabResource
---@overload fun(self: ResourceCache, typeName: "Resource", resourceName: string): Resource
---@overload fun(self: ResourceCache, typeName: "Sound", resourceName: string): Sound
---@overload fun(self: ResourceCache, typeName: "Sprite2D", resourceName: string): Sprite2D
---@overload fun(self: ResourceCache, typeName: "Technique", resourceName: string): Technique
---@overload fun(self: ResourceCache, typeName: "Texture", resourceName: string): Texture
---@overload fun(self: ResourceCache, typeName: "Texture2D", resourceName: string): Texture2D
---@overload fun(self: ResourceCache, typeName: "TmxFile2D", resourceName: string): TmxFile2D
---@overload fun(self: ResourceCache, typeName: "XMLFile", resourceName: string): XMLFile
---@param typeName string
---@param resourceName string
---@return Resource
function ResourceCache:GetResource(typeName, resourceName) end
---@return string
function ResourceCache.GetResourceFileName(...) end
function ResourceCache.ReleaseResource(...) end

---@class RibbonTrail : Drawable, Component, Serializable, Object
RibbonTrail = {}
function RibbonTrail.GetTrailType(...) end
function RibbonTrail.IsEmitting(...) end
function RibbonTrail.SetEmitting(...) end
function RibbonTrail.SetEndColor(...) end
function RibbonTrail.SetLifetime(...) end
function RibbonTrail.SetMaterial(...) end
function RibbonTrail.SetStartColor(...) end
function RibbonTrail.SetTailColumn(...) end
function RibbonTrail.SetTrailType(...) end
function RibbonTrail.SetUpdateInvisible(...) end
function RibbonTrail.SetWidth(...) end

---@class RigidBody : Component, Serializable, Object
RigidBody = {}
function RigidBody.Activate(...) end
function RigidBody.ApplyForce(...) end
function RigidBody.ApplyImpulse(...) end
function RigidBody.ApplyTorque(...) end
function RigidBody.ApplyTorqueImpulse(...) end
function RigidBody.DrawDebugGeometry(...) end
function RigidBody.GetAngularVelocity(...) end
function RigidBody.GetLinearVelocity(...) end
function RigidBody.GetMass(...) end
function RigidBody.GetRotation(...) end
function RigidBody.ResetForces(...) end
function RigidBody.SetAngularDamping(...) end
function RigidBody.SetAngularFactor(...) end
function RigidBody.SetAngularRestThreshold(...) end
function RigidBody.SetAngularVelocity(...) end
function RigidBody.SetCcdMotionThreshold(...) end
function RigidBody.SetCcdRadius(...) end
function RigidBody.SetCollisionEventMode(...) end
function RigidBody.SetCollisionLayer(...) end
function RigidBody.SetCollisionLayerAndMask(...) end
function RigidBody.SetCollisionMask(...) end
function RigidBody.SetContactProcessingThreshold(...) end
function RigidBody.SetFriction(...) end
function RigidBody.SetKinematic(...) end
function RigidBody.SetLinearDamping(...) end
function RigidBody.SetLinearRestThreshold(...) end
function RigidBody.SetLinearVelocity(...) end
function RigidBody.SetMass(...) end
function RigidBody.SetRestitution(...) end
function RigidBody.SetRollingFriction(...) end
function RigidBody.SetTrigger(...) end
function RigidBody.SetUseGravity(...) end

---@class RigidBody2D : Component, Serializable, Object
RigidBody2D = {}
function RigidBody2D.ApplyAngularImpulse(...) end
function RigidBody2D.ApplyForce(...) end
function RigidBody2D.ApplyForceToCenter(...) end
function RigidBody2D.ApplyLinearImpulse(...) end
function RigidBody2D.ApplyLinearImpulseToCenter(...) end
function RigidBody2D.ApplyTorque(...) end
function RigidBody2D.GetBodyType(...) end
function RigidBody2D.GetLinearVelocity(...) end
function RigidBody2D.GetMass(...) end
function RigidBody2D.GetMassCenter(...) end
function RigidBody2D.SetAllowSleep(...) end
function RigidBody2D.SetAngularDamping(...) end
function RigidBody2D.SetAngularVelocity(...) end
function RigidBody2D.SetAwake(...) end
function RigidBody2D.SetBodyType(...) end
function RigidBody2D.SetBullet(...) end
function RigidBody2D.SetFixedRotation(...) end
function RigidBody2D.SetGravityScale(...) end
function RigidBody2D.SetInertia(...) end
function RigidBody2D.SetLinearDamping(...) end
function RigidBody2D.SetLinearVelocity(...) end
function RigidBody2D.SetMass(...) end
function RigidBody2D.SetMassCenter(...) end
function RigidBody2D.SetUseFixtureMass(...) end

---@class SOUND
SOUND = {}
SOUND.AMBIENT = 0
SOUND.EFFECT = 0
SOUND.MASTER = 0
SOUND.MUSIC = 0

---@class Scene : Node, Serializable, Object
Scene = {}
function Scene.Clear(...) end
---@return Node
function Scene.GetChildByIndex(...) end
function Scene.GetTimeScale(...) end
function Scene.GetWorldOrigin(...) end
function Scene.InstantiateXML(...) end
function Scene.IsUpdateEnabled(...) end
---@return boolean
function Scene.Load(...) end
---@return boolean
function Scene.LoadXML(...) end
---@return boolean
function Scene.Save(...) end
function Scene.SetTimeScale(...) end
function Scene.SetUpdateEnabled(...) end

---@class Serializable : Object
Serializable = {}
function Serializable.GetAttribute(...) end
function Serializable.GetAttributes(...) end
function Serializable.LoadXML(...) end
function Serializable.SetAttribute(...) end

---@class Skeleton
Skeleton = {}
---@return Bone
function Skeleton.GetBone(...) end
function Skeleton.GetNumBones(...) end

---@class Skybox : StaticModel, Drawable, Component, Serializable, Object
Skybox = {}

---@class Slider : BorderImage, UIElement, Serializable, Object
Slider = {}
function Slider.GetValue(...) end
function Slider.SetRange(...) end
function Slider.SetValue(...) end

---@class Sound : Resource, Object
Sound = {}
function Sound.SetLooped(...) end

---@class SoundListener : Component, Serializable, Object
SoundListener = {}

---@class SoundSource : Component, Serializable, Object
SoundSource = {}
function SoundSource.IsPlaying(...) end
function SoundSource.Play(...) end
function SoundSource.SetAttenuation(...) end
function SoundSource.SetAutoRemoveMode(...) end
function SoundSource.SetFrequency(...) end
function SoundSource.SetGain(...) end
function SoundSource.SetIgnoreSceneTimeScale(...) end
function SoundSource.SetLowFrequency(...) end
function SoundSource.SetPanning(...) end
function SoundSource.SetReach(...) end
function SoundSource.SetSoundType(...) end
function SoundSource.Stop(...) end

---@class SoundSource3D : SoundSource, Component, Serializable, Object
SoundSource3D = {}
function SoundSource3D.SetFarDistance(...) end
function SoundSource3D.SetNearDistance(...) end

---@class SoundStream
SoundStream = {}
function SoundStream.GetFrequency(...) end
function SoundStream.GetSampleSize(...) end
function SoundStream.SetFormat(...) end
function SoundStream.SetStopAtEnd(...) end

---@class Sprite : UIElement, Serializable, Object
Sprite = {}
function Sprite.GetRotation(...) end
function Sprite.SetBlendMode(...) end
function Sprite.SetHotSpot(...) end
function Sprite.SetImageRect(...) end
function Sprite.SetRotation(...) end
function Sprite.SetScale(...) end
function Sprite.SetTexture(...) end

---@class Sprite2D : Resource, Object
Sprite2D = {}

---@class StaticModel : Drawable, Component, Serializable, Object
StaticModel = {}
function StaticModel.GetMaterial(...) end
function StaticModel.GetModel(...) end
function StaticModel.SetMaterial(...) end
function StaticModel.SetModel(...) end

---@class StaticModelGroup : StaticModel, Drawable, Component, Serializable, Object
StaticModelGroup = {}
function StaticModelGroup.AddInstanceNode(...) end
function StaticModelGroup.GetInstanceNode(...) end
function StaticModelGroup.GetNumInstanceNodes(...) end
function StaticModelGroup.RemoveInstanceNode(...) end

---@class StaticSprite2D : Drawable2D, Drawable, Component, Serializable, Object
StaticSprite2D = {}
function StaticSprite2D.GetSprite(...) end
function StaticSprite2D.SetBlendMode(...) end
function StaticSprite2D.SetColor(...) end
function StaticSprite2D.SetFlip(...) end
function StaticSprite2D.SetFlipX(...) end
function StaticSprite2D.SetFlipY(...) end
function StaticSprite2D.SetHotSpot(...) end
function StaticSprite2D.SetSprite(...) end
function StaticSprite2D.SetUseHotSpot(...) end

---@class StretchableSprite2D : StaticSprite2D, Drawable2D, Drawable, Component, Serializable, Object
StretchableSprite2D = {}
function StretchableSprite2D.SetBorder(...) end

---@class TE
TE = {}
TE.NONE = 0
TE.SHADOW = 0
TE.STROKE = 0

---@class TEXF
TEXF = {}
TEXF.BGRA8_UNORM = 0
TEXF.D24S8 = 0
TEXF.D32 = 0
TEXF.R32_FLOAT = 0
TEXF.R8_UNORM = 0
TEXF.RG16_UNORM = 0
TEXF.RGBA16_FLOAT = 0
TEXF.RGBA32_FLOAT = 0
TEXF.RGBA8_UNORM = 0
TEXF.RGBA8_UNORM_SRGB = 0

---@class TS
TS = {}
TS.LOCAL = 0
TS.PARENT = 0
TS.WORLD = 0

---@class TT
TT = {}
TT.BONE = 0
TT.FACE_CAMERA = 0

---@class Technique : Resource, Object
Technique = {}

---@class Terrain : Component, Serializable, Object
Terrain = {}
function Terrain.GetHeight(...) end
function Terrain.GetNormal(...) end
---@return boolean
function Terrain.SetHeightMap(...) end
function Terrain.SetMaterial(...) end
function Terrain.SetOccluder(...) end
function Terrain.SetPatchSize(...) end
function Terrain.SetSmoothing(...) end
function Terrain.SetSpacing(...) end

---@class Text : UIElement, Serializable, Object
Text = {}
function Text.GetNumRows(...) end
function Text.GetRowHeight(...) end
function Text.GetRowWidth(...) end
function Text.SetAutoLocalizable(...) end
function Text.SetEffectColor(...) end
function Text.SetEffectDepthBias(...) end
---@return boolean
function Text.SetFont(...) end
function Text.SetFontSize(...) end
function Text.SetRowSpacing(...) end
function Text.SetText(...) end
function Text.SetTextAlignment(...) end
function Text.SetTextEffect(...) end
function Text.SetWordwrap(...) end

---@class Text3D : Drawable, Component, Serializable, Object
Text3D = {}
function Text3D.SetAlignment(...) end
function Text3D.SetColor(...) end
function Text3D.SetEffectColor(...) end
---@return boolean
function Text3D.SetFont(...) end
function Text3D.SetFontSize(...) end
function Text3D.SetText(...) end
function Text3D.SetTextAlignment(...) end
function Text3D.SetTextEffect(...) end

---@class Texture : Resource, Object
Texture = {}
function Texture.GetHeight(...) end
---@return RenderSurface
function Texture.GetRenderSurface(...) end
function Texture.GetWidth(...) end
function Texture.SetFilterMode(...) end

---@class Texture2D : Texture, Resource, Object
Texture2D = {}
---@return boolean
function Texture2D.SetSize(...) end

---@class Tile2D
Tile2D = {}
function Tile2D.GetFlipX(...) end
function Tile2D.GetFlipY(...) end
function Tile2D.GetGid(...) end
---@return string
function Tile2D.GetProperty(...) end
function Tile2D.GetSprite(...) end

---@class TileMap2D : Component, Serializable, Object
TileMap2D = {}
function TileMap2D.DrawDebugGeometry(...) end
---@return TileMapInfo2D
function TileMap2D.GetInfo(...) end
function TileMap2D.GetLayer(...) end
function TileMap2D.GetNumLayers(...) end
function TileMap2D.PositionToTileIndex(...) end
function TileMap2D.SetTmxFile(...) end
function TileMap2D.TileIndexToPosition(...) end

---@class TileMapInfo2D
TileMapInfo2D = {}
function TileMapInfo2D.GetMapHeight(...) end
function TileMapInfo2D.GetMapWidth(...) end
TileMapInfo2D.height = nil
TileMapInfo2D.orientation = nil
TileMapInfo2D.tileHeight = nil
TileMapInfo2D.tileWidth = nil
TileMapInfo2D.width = nil

---@class TileMapLayer2D : Component, Serializable, Object
TileMapLayer2D = {}
function TileMapLayer2D.GetHeight(...) end
function TileMapLayer2D.GetImageNode(...) end
function TileMapLayer2D.GetLayerType(...) end
function TileMapLayer2D.GetNumObjects(...) end
function TileMapLayer2D.GetObject(...) end
function TileMapLayer2D.GetObjectNode(...) end
---@return string
function TileMapLayer2D.GetProperty(...) end
function TileMapLayer2D.GetTile(...) end
function TileMapLayer2D.GetTileMap(...) end
function TileMapLayer2D.GetTileNode(...) end
function TileMapLayer2D.GetWidth(...) end
function TileMapLayer2D.HasProperty(...) end
function TileMapLayer2D.IsVisible(...) end
function TileMapLayer2D.SetVisible(...) end

---@class TileMapObject2D
TileMapObject2D = {}
function TileMapObject2D.GetName(...) end
function TileMapObject2D.GetNumPoints(...) end
function TileMapObject2D.GetObjectType(...) end
function TileMapObject2D.GetPoint(...) end
function TileMapObject2D.GetPosition(...) end
---@return string
function TileMapObject2D.GetProperty(...) end
function TileMapObject2D.GetSize(...) end
function TileMapObject2D.GetTileGid(...) end
function TileMapObject2D.GetTileSprite(...) end
function TileMapObject2D.GetType(...) end
---@return boolean
function TileMapObject2D.HasProperty(...) end

---@class Time : Object
Time = {}
function Time.GetElapsedTime(...) end
function Time.GetFrameNumber(...) end
function Time.GetFramesPerSecond(...) end
function Time.GetSystemTime(...) end
function Time.GetTimeSinceEpoch(...) end
function Time.GetTimeStep(...) end
Time.timeStep = nil

---@class TmxFile2D : Resource, Object
TmxFile2D = {}

---@class ToolTip : UIElement, Serializable, Object
ToolTip = {}

---@class TouchState
TouchState = {}
TouchState.delta = nil
TouchState.lastPosition = nil
TouchState.position = nil
TouchState.pressure = nil
TouchState.touchID = nil

---@class UI : Object
UI = {}
function UI.ConvertUIToSystem(...) end
function UI.DebugDraw(...) end
function UI.GetCursor(...) end
function UI.GetElementAt(...) end
function UI.GetFocusElement(...) end
function UI.GetFontHintLevel(...) end
function UI.GetFontOversampling(...) end
function UI.GetFontSubpixelThreshold(...) end
function UI.GetForceAutoHint(...) end
function UI.GetRoot(...) end
function UI.GetRootModalElement(...) end
function UI.GetUICursorPosition(...) end
function UI.LoadLayout(...) end
function UI.SetCursor(...) end
function UI.SetFontHintLevel(...) end
function UI.SetFontOversampling(...) end
function UI.SetFontSubpixelThreshold(...) end
function UI.SetForceAutoHint(...) end
function UI.SetScale(...) end
function UI.SetUseSystemClipboard(...) end

---@class UIComponent : Component, Serializable, Object
UIComponent = {}
function UIComponent.GetMaterial(...) end
function UIComponent.GetRoot(...) end

---@class UIElement : Serializable, Object
UIElement = {}
function UIElement.AddChild(...) end
function UIElement.AddTag(...) end
function UIElement.BringToFront(...) end
function UIElement.CreateChild(...) end
function UIElement.GetChild(...) end
---@return table
function UIElement.GetChildren(...) end
---@return table
function UIElement.GetChildrenWithTag(...) end
function UIElement.GetHeight(...) end
function UIElement.GetMinWidth(...) end
---@return string
function UIElement.GetName(...) end
function UIElement.GetParent(...) end
function UIElement.GetPosition(...) end
function UIElement.GetSize(...) end
function UIElement.GetVar(...) end
function UIElement.GetWidth(...) end
function UIElement.HasFocus(...) end
function UIElement.HasTag(...) end
function UIElement.IsVisible(...) end
function UIElement.RemoveAllChildren(...) end
function UIElement.RemoveChild(...) end
function UIElement.SetAlignment(...) end
function UIElement.SetAttributeAnimation(...) end
function UIElement.SetBringToFront(...) end
function UIElement.SetColor(...) end
function UIElement.SetDefaultStyle(...) end
function UIElement.SetEnabled(...) end
function UIElement.SetFixedHeight(...) end
function UIElement.SetFixedSize(...) end
function UIElement.SetFixedWidth(...) end
function UIElement.SetFocus(...) end
function UIElement.SetFocusMode(...) end
function UIElement.SetHeight(...) end
function UIElement.SetHorizontalAlignment(...) end
function UIElement.SetLayout(...) end
function UIElement.SetLayoutBorder(...) end
function UIElement.SetLayoutMode(...) end
function UIElement.SetLayoutSpacing(...) end
function UIElement.SetMaxHeight(...) end
function UIElement.SetMaxSize(...) end
function UIElement.SetMaxWidth(...) end
function UIElement.SetMinHeight(...) end
function UIElement.SetMinSize(...) end
function UIElement.SetMinWidth(...) end
function UIElement.SetName(...) end
function UIElement.SetOpacity(...) end
function UIElement.SetPosition(...) end
function UIElement.SetPriority(...) end
function UIElement.SetSize(...) end
---@return boolean
function UIElement.SetStyle(...) end
---@return boolean
function UIElement.SetStyleAuto(...) end
function UIElement.SetTemporary(...) end
function UIElement.SetUseDerivedOpacity(...) end
function UIElement.SetVar(...) end
function UIElement.SetVerticalAlignment(...) end
function UIElement.SetVisible(...) end
function UIElement.SetWidth(...) end
function UIElement.UpdateLayout(...) end

---@class VA
VA = {}
VA.BOTTOM = 0
VA.CENTER = 0
VA.TOP = 0

---@class VET
VET = {}
VET.FLOAT = 0
VET.INT = 0
VET.UBYTE4 = 0
VET.UBYTE4_NORM = 0
VET.VECTOR2 = 0
VET.VECTOR3 = 0
VET.VECTOR4 = 0

---@class VO
VO = {}
VO.DISABLE_OCCLUSION = 0
VO.NO_SHADOWS = 0

---@class VSEM
VSEM = {}
VSEM.BINORMAL = 0
VSEM.BLENDINDICES = 0
VSEM.BLENDWEIGHTS = 0
VSEM.COLOR = 0
VSEM.NORMAL = 0
VSEM.OBJECTINDEX = 0
VSEM.POSITION = 0
VSEM.TANGENT = 0
VSEM.TEXCOORD = 0

---@class ValueAnimation
ValueAnimation = {}
function ValueAnimation.SetEventFrame(...) end
function ValueAnimation.SetKeyFrame(...) end

---@class VariantMapView
VariantMapView = {}
function VariantMapView.Contains(...) end

---@class Vector2
Vector2 = {}
function Vector2.Angle(...) end
function Vector2.Dot(...) end
function Vector2.Length(...) end
function Vector2.LengthSquared(...) end
function Vector2.Lerp(...) end
function Vector2.Normalized(...) end
Vector2.DOWN = nil
Vector2.LEFT = nil
Vector2.ONE = nil
Vector2.RIGHT = nil
Vector2.UP = nil
Vector2.ZERO = nil
Vector2.x = nil
Vector2.y = nil

---@class Vector3
Vector3 = {}
function Vector3.Angle(...) end
function Vector3.Cross(...) end
function Vector3.CrossProduct(...) end
function Vector3.Dot(...) end
function Vector3.DotProduct(...) end
function Vector3.FromXZ(...) end
function Vector3.Length(...) end
function Vector3.LengthSquared(...) end
function Vector3.Lerp(...) end
function Vector3.Normalized(...) end
Vector3.BACK = nil
Vector3.DOWN = nil
Vector3.FORWARD = nil
Vector3.LEFT = nil
Vector3.ONE = nil
Vector3.RIGHT = nil
Vector3.UP = nil
Vector3.ZERO = nil
Vector3.x = nil
Vector3.y = nil
Vector3.z = nil

---@class Vector4
Vector4 = {}
Vector4.ONE = nil
Vector4.ZERO = nil
Vector4.w = nil
Vector4.x = nil
Vector4.y = nil
Vector4.z = nil

---@class VectorBuffer
VectorBuffer = {}
function VectorBuffer.Clear(...) end
function VectorBuffer.GetSize(...) end
function VectorBuffer.ReadFloat(...) end
function VectorBuffer.ReadString(...) end
function VectorBuffer.ReadVLE(...) end
function VectorBuffer.Seek(...) end
function VectorBuffer.WriteFloat(...) end
function VectorBuffer.WriteString(...) end
function VectorBuffer.WriteVLE(...) end

---@class VertexBuffer
VertexBuffer = {}
function VertexBuffer.GetVertexCount(...) end
---@return table
function VertexBuffer.GetVertexPositions(...) end
function VertexBuffer.GetVertexSize(...) end
function VertexBuffer.SetDebugName(...) end
function VertexBuffer.SetShadowed(...) end
function VertexBuffer.SetSize(...) end
function VertexBuffer.Update(...) end
function VertexBuffer.UpdateVertexPositions(...) end

---@class VertexElement
VertexElement = {}
VertexElement.index = nil
VertexElement.semantic = nil
VertexElement.type = nil

---@class Viewport : Object
Viewport = {}
function Viewport.GetCamera(...) end
function Viewport.GetScene(...) end
function Viewport.SetCamera(...) end
function Viewport.SetRect(...) end
function Viewport.SetScene(...) end

---@class WMODE
WMODE = {}
WMODE.BORDERLESS = 0
WMODE.FULLSCREEN = 0
WMODE.WINDOWED = 0

---@class Window : BorderImage, UIElement, Serializable, Object
Window = {}
function Window.SetModal(...) end
function Window.SetMovable(...) end

---@class XMLFile : Resource, Object
XMLFile = {}

---@class Zone : Drawable, Component, Serializable, Object
Zone = {}
function Zone.SetAmbientColor(...) end
function Zone.SetBoundingBox(...) end
function Zone.SetFogColor(...) end
function Zone.SetFogEnd(...) end
function Zone.SetFogStart(...) end
function Zone.SetHeightFog(...) end
function Zone.SetPriority(...) end
